### ISSUE TITLE
Nodejs Version

### ISSUE THREAD

**Issue by cdiaz** [mutantzombie/JavaScript-ViewState-Parser#1]
You can make a version for nodejs?

**Comment by mutantzombie** [comment]
...maybe. My outlook on ViewState is that it's pretty dead and not the best approach for modern apps. So this hasn't been a priority for me to revisit. I'm curious what the prevalence is of sites with ViewState that have been written in the last 3/5/10 years. (Mostly a rhetorical question; no idea how to go about collecting such data.)

**Comment by cdiaz** [comment]
Some government websites in Colombia do not provide web services, so we do scraping, and they return viewstates
Then we solve it with selenium, and phanthomjs.
But we want to find a tool for treating viewstates in nodejs
